### PR TITLE
Merging gittip message into genesis branch

### PR DESCRIPTION
**Pull request by JaimeLynSchatz**
I think (hope) this is what you meant :)

### CODE REVIEW

**Comment by sdboyer** [comment]
not quite, but that's all right! i'll cherry-pick it :)

**Comment by quicksketch** [comment]
LOL, better get ready to see a lot of PRs like this @sdboyer. ;)

...still laughing.

**Comment by sdboyer** [comment]
@quicksketch yeah :) i know how i need to refactor this to make it smoother, but i'm not sure i care enough to do it... :sleeping:

**Comment by sdboyer** [comment]
aaand it's in.

**Pull request closed without merging**
